name: Feature Request
about: Suggest an idea for this project
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe your idea below.
  - type: input
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
      placeholder: Feature description
    validations:
      required: true
  - type: input
    id: mc_version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you using?
      placeholder: e.g. 1.20.1
    validations:
      required: true
  - type: input
    id: mod_version
    attributes:
      label: Mod Version
      description: What version of the mod are you using?
      placeholder: e.g. 1.0.0
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Additional Details
      description: Any other details or context?
      placeholder: More information
